names = ["Drogon","Caraxes","Vermithor","Cannibel","Syrax","Vhagar"]
print(names)
names.append("Belaryon")
print(names)
names.sort()
print(names)
names.sort(reverse=True)
print(names)
names.reverse()
print(names)
names.insert(2,"Rhagar")
print(names)
names.remove("Rhagar")
print(names)
names.pop(3)
print(names)