f2 = open("13.FileOperations/sample.txt", "w")
data = f2.write("I am overwriting everything ....")
f2.close()
f = open("13.FileOperations/sample.txt", "rt")
data = f.read()
print(data)
print(type(data))
f.close()
f3 = open("13.FileOperations/sample.txt", "a")
data = f3.write("\nI am just appendingggg.....")
f3.close()
